### PR TITLE
Modified button

### LINKED ISSUE #82: Change Google Sign In button
## Description
Change the Google sign-in button to a broader one.

## Current  Screenshots
image

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Remove the Facebook button
2. Change the Google button UI using  https://pub.dev/packages/flutter_signin_button

## Additional data
None

### PR DESCRIPTION
**Pull request by Sayam06**
# Description

Summary of the changes and which issue is fixed.

Fixes #82,  removed facebook button and added google button.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the code of conduct of this project
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
@Sayam06 please comment on the issue first to get yourselves assigned.

**Comment by Sayam06** [comment]
can i please work on this issue?

**Comment by Mohitmadhav** [comment]
@Sayam06 , Read the guidelines and comment on the issue, tagging me. I'll assign  you and check the PR

**Comment by Mohitmadhav** [comment]
> Removed the Facebook button and modified the google button.

@Sayam06  please follow the PR template and edit your submission. The PR is fine

**Comment by Sayam06** [comment]
> > Removed the Facebook button and modified the google button.
> 
> @Sayam06 please follow the PR template and edit your submission. The PR is fine

@Mohitmadhav can you tell me where I can find the template? Or should I create a new PR to get the template?

**Comment by Mohitmadhav** [comment]
> > > Removed the Facebook button and modified the google button.
> > 
> > 
> > @Sayam06 please follow the PR template and edit your submission. The PR is fine
> 
> @Mohitmadhav can you tell me where I can find the template? Or should I create a new PR to get the template?

While creating a new pull request, you'll see the format 
Then copy-paste that format in this PR.
No need to create a new PR, just copy the format

**Comment by Sayam06** [comment]
@Mohitmadhav is this okay? None of the options in "Type of change" were applicable so I left them blank.

**Comment by Mohitmadhav** [comment]
Cool @Sayam06!! But from now on, strictly follow the linting rules and standard practices to avoid warnings.
For more details see: analysis_options.yaml
I'm merging this PR.

**Comment by Mohitmadhav** [comment]
> @Mohitmadhav is this okay? None of the options in "Type of change" were applicable so I left them blank.

No problem, I mentioned it.

**Comment by Sayam06** [comment]
> Cool @Sayam06!! But from now on, strictly follow the linting rules and standard practices to avoid warnings. For more details see: analysis_options.yaml I'm merging this PR.

Thanks :)
And sure, I'll follow the standard practices next time.
Cheers!!

**Comment by Mohitmadhav** [comment]
> > Cool @Sayam06!! But from now on, strictly follow the linting rules and standard practices to avoid warnings. For more details see: analysis_options.yaml I'm merging this PR.
> 
> Thanks :) And sure, I'll follow the standard practices next time. Cheers!!

Yeah, more issues will be created.

**Pull request merged**
