### PR TITLE
add LogIn and Logout

### LINKED ISSUE #101: Email Login and Logout
## Description
To implement Email Login in the Initial Screen. Currently, it's resulting in null uid as shown below.

## Screenshots

<div class = "row">

</div>

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Initial screen : lib\screens\initial_screen.dart
2. Auth files: lib\services\auth.dart
3. Also implement the email log out when the user taps on the logout button.
4. Private profile: lib\screens\profile\private_profile.dart

## Additional data
None

### PR DESCRIPTION
**Pull request by keyurgit45**
# Description
This PR will add the login and logout feature. also after 2 days of inactivity, the user will get logged out automatically and the user has to log in again. I have tested the app by taking 2 minutes of time for session expiration.

Summary of the changes and which issue is fixed. 

Fixes #101

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the code of conduct of this project
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
@keyurgit45 does it use Gmail password for logging in?

**Comment by keyurgit45** [comment]
> @keyurgit45 does it use the Gmail password for logging in? It's telling wrong password

It uses the same email and password which the user has given while registering/sign up.

**Comment by Mohitmadhav** [comment]
image

Don't know why but my name isn't showing here, and I tried all passwords and none is getting accepted.

**Comment by Mohitmadhav** [comment]
> > @keyurgit45 does it use the Gmail password for logging in? It's telling wrong password
> 
> It uses the same email and password which the user has given while registering/sign up. please do not register with a new email until we fix #106 coz profile page will not load

For sure I won't.

**Comment by keyurgit45** [comment]
> image
> 
> Don't know why but my name isn't showing here, and I tried all passwords and none is getting accepted.

ohhh..try for test123@gmail.com => test@1234

**Comment by Mohitmadhav** [comment]
No need now, I fixed it through the Firebase console...Thanks!!
Also, I recommend you to go for the *Forgot your password* setup after #106 so the code would remain modular because only 1 person would be looking after the auth part. 

Then we can go for Firebase at a later stage if you would be interested.

**Comment by keyurgit45** [comment]
> No need now, I fixed it through the Firebase console...Thanks!! Also, I recommend you to go for the _Forgot your password_ setup after #106 so the code would remain modular because only 1 person would be looking after the auth part.
> 
> Then we can go for Firebase at a later stage if you would be interested.

Sure, I would like to contribute.

**Review by Mohitmadhav — APPROVED** [review]

**Pull request merged**
