### PR TITLE
Revamped Book and User Collections

### LINKED ISSUE #92: Revamp Firebase Database and Provider Functions
## Description
We need to make two Collections
1. Books 
 *  Book ISBN Number (unique identification),
 *  Book Name, 
 *  Book Author, 
 *  Book Genre, 
 *  Book Owner (Will contain uid of user who is inputting the book), 
 *  Book Description, Book Photo  
 
 **Apart from ISBN and Book Owner all fields can be null**

2. User 
* User name, 
* Location (lat,long), 
* User photo, 
* User bio, 
* User Genre Preference (top 3 preference)
 
**If there are other things then add in case of user**

## Screenshots
None

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Database files: lib/services/database_service.dart
2. User and Book Providers: lib/providers

## Additional data
We can have a discussion on <a href = "https://github.com/Project-Easter/Flutter-UI/discussions/91">Code Refactoring</a> if required.

### PR DESCRIPTION
**Pull request by keyurgit45**
# Description
Revamped books and user collection. added given fields. earlier add book button was not working. Fixed add book button functionality. Now when a user adds a book, it gets added in both users and books collections under owned books. (as per discussion)
Summary of the changes and which issue is fixed. 

Fixes #92

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the code of conduct of this project
- [x My code follows the style guidelines of this project
- [x] My changes generate no new warnings
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
> @Mohitmadhav It is working on my device. did you add this ISBN no: 9780062416216?

Mine is: 9788172234980

**Comment by Mohitmadhav** [comment]
Even Google is saying that.
Let's see how to resolve this

**Comment by keyurgit45** [comment]
@Mohitmadhav I referred to the google API docs. maybe I found a solution.
we need to modify the URL: https://www.googleapis.com/books/v1/volumes?q=the%20alchemist+isbn:9788172234980
ref: https://developers.google.com/books/docs/v1/using#ids

**Comment by Mohitmadhav** [comment]
Yeah got it.

**Pull request merged**
