### PR TITLE
Fix for error showing on dashboard

### PR DESCRIPTION
**Pull request by RandyKdev**
# Description

This problem occurs when logged in and the dashboard is open, for some reason the snapshot.data received from the call to topBooks in file dashboard.dart is null.

So when null is passed to BookList widget as the second argument, the following error shows up as on the screenshot below

Screenshot_20211005-010538

due to calling the shuffle method on null and length method on null in the book_list.dart file

After doing the changes, Here is how it looks and functions when it is null

Screenshot_20211005-013602

I understand that there could be improvements to this, like showing a message which says "No new books to discover"

If there are any modifications or suggestions to this, I would be glad to add them.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the code of conduct of this project
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
@RandyKdev it's already described in #38.
Please follow the README guidelines properly. 
I'll review the PR once you get the issue assigned.

**Comment by RandyKdev** [comment]
Ok, thanks. I didn't know there was issue like that.

Thanks.

**Comment by RandyKdev** [comment]
I have updated this PR to reflect recent commits to main.

**Comment by RandyKdev** [comment]
I am closing this because I discovered that I didn't create my own branch before making the changes.

**Pull request closed without merging**
