### PR TITLE
Fix: Incompatibility library version and Undefined Properties

### PR DESCRIPTION
**Pull request by yusriltakeuchi**
# Description

Your project using sdk: ">=2.7.0 <3.0.0" and not updated to null safety, i found some library doesn't match with current SDK because the library version is for null safety version.
So i downgrade some library to support current SDK.
Also i found some error because the properties is undefined.

Fixes # (issue)

## Type of change

- [x] Downgrade incompatibility library version
- [x] Fix error undefined properties

## Notes
Please label this PR as for hacktoberfest, thank you.

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
Yes, @yusriltakeuchi I was going to create an issue on this, and I just now upgraded to Flutter 2.5.2 and Dart 2.14.3.
Anyways, you can create an issue for this by adding the screenshots (Mentioned in the issue template)
Then I'll add the labels and assign it to you.

Thanks.

**Comment by Mohitmadhav** [comment]
> Yes, @yusriltakeuchi I was going to create an issue on this, and I just now upgraded to Flutter 2.5.2 and Dart 2.14.3. Anyways, you can create an issue for this by adding the screenshots (Mentioned in the issue template) Then I'll add the labels and assign it to you.
> 
> Thanks.

I think null safety migration might do.

**Comment by yusriltakeuchi** [comment]
> > Yes, @yusriltakeuchi I was going to create an issue on this, and I just now upgraded to Flutter 2.5.2 and Dart 2.14.3. Anyways, you can create an issue for this by adding the screenshots (Mentioned in the issue template) Then I'll add the labels and assign it to you.
> > Thanks.
> 
> I think null safety migration might do.

So you want to migrate this to null safety? Can you accept this PR first? after that i will working with new null safety version from your PR

**Comment by Mohitmadhav** [comment]
> > > Yes, @yusriltakeuchi I was going to create an issue on this, and I just now upgraded to Flutter 2.5.2 and Dart 2.14.3. Anyways, you can create an issue for this by adding the screenshots (Mentioned in the issue template) Then I'll add the labels and assign it to you.
> > > Thanks.
> > 
> > 
> > I think null safety migration might do.
> 
> So you want to migrate this to null safety? Can you accept this PR first? after that i will working with new null safety version from your PR

I am checking other issues and README for the app. Till then you yourself create an issue for this and tag me there to allot it to you. Then I'll add the labels, allot the issue, and merge this PR

**Comment by Mohitmadhav** [comment]
> > > > Yes, @yusriltakeuchi I was going to create an issue on this, and I just now upgraded to Flutter 2.5.2 and Dart 2.14.3. Anyways, you can create an issue for this by adding the screenshots (Mentioned in the issue template) Then I'll add the labels and assign it to you.
> > > > Thanks.
> > > 
> > > 
> > > I think null safety migration might do.
> > 
> > 
> > So you want to migrate this to null safety? Can you accept this PR first? after that i will working with new null safety version from your PR
> 
> @yusriltakeuchi I am checking other issues and README for the app. Till then you yourself create an issue for this and tag me there to assign it to you. Then I'll add the labels, allot the issue, and merge this PR

Also @yusriltakeuchi,  you can also create the null safety issue. Then I'll assign that issue to you after I merge this PR. Contributors are always welcome to create issues and suggest new features. 

PS: I'll rectify the syntactical errors anyways.

**Comment by yusriltakeuchi** [comment]
@Mohitmadhav so now i must create issue first and tag you and this PR in there?

**Comment by Mohitmadhav** [comment]
> @Mohitmadhav so now i must create issue first and tag you and this PR in there?

No, just tag me in the comment after creating the issue, don't add the PR in there. 
Also if you can add the screenshots it would be better

**Review by Mohitmadhav — CHANGES_REQUESTED** [review]
image

@yusriltakeuchi the app isn't running. Please check out what's the problem.
I also tried the *flutter clean* command but it didn't work. I think its again the null safety issue.

**Comment by yusriltakeuchi** [comment]
> image
> 
> @yusriltakeuchi the app isn't running. Please check out what's the problem. I also tried the _flutter clean_ command but it didn't work. I think its again the null safety issue.

You're using flutter 2.5 in your vscode, and the app is not migrated into null safety.
Please try using flutter 1.22.6 version

you can use https://github.com/leoafarias/fvm to download lower sdk version without getting impact with current sdk

**Comment by Mohitmadhav** [comment]
> > image
> > @yusriltakeuchi the app isn't running. Please check out what's the problem. I also tried the _flutter clean_ command but it didn't work. I think its again the null safety issue.
> 
> You're using flutter 2.5 in your vscode, and the app is not migrated into null safety. Please try using flutter 1.22.6 version
> 
> you can use https://github.com/leoafarias/fvm to download lower sdk version without getting impact with current sdk

Can't it be resolved without downgrading bro? Because we should operate in the latest version.

**Comment by yusriltakeuchi** [comment]
> Can't it be resolved without downgrading bro? Because we should operate in the latest version.

yep, the best solution is migrating this applications first.
Do you want to migrate this to null safety? You can close this PR and i will create new PR after your code published.

**Comment by Mohitmadhav** [comment]
> > Can't it be resolved without downgrading bro? Because we should operate in the latest version.
> 
> yep, the best solution is migrating this applications first. Do you want to migrate this to null safety? You can close this PR and i will create new PR after your code published.

Yep, that's why I told for null safety migration in the first place and to keep the latest Flutter version. 
When you'll migrate to null saftey there will be a few errors. Once you resolve that...it's done.

**Comment by yusriltakeuchi** [comment]
> > > Can't it be resolved without downgrading bro? Because we should operate in the latest version.
> > 
> > 
> > yep, the best solution is migrating this applications first. Do you want to migrate this to null safety? You can close this PR and i will create new PR after your code published.
> 
> Yep, that's why I told for null safety migration in the first place and to keep the latest Flutter version. When you'll migrate to null saftey there will be a few errors. Once you resolve that...it's done.

Okay, i will wait your latest code with null safety support.

**Comment by Mohitmadhav** [comment]
> > > > Can't it be resolved without downgrading bro? Because we should operate in the latest version.
> > > 
> > > 
> > > yep, the best solution is migrating this applications first. Do you want to migrate this to null safety? You can close this PR and i will create new PR after your code published.
> > 
> > 
> > Yep, that's why I told for null safety migration in the first place and to keep the latest Flutter version. When you'll migrate to null saftey there will be a few errors. Once you resolve that...it's done.
> 
> Okay, i will wait your latest code with null safety support.

- Yeah @yusriltakeuchi , first pull the updated code through *git pull upstream main*,  
- Then migrate the app to null safety with Flutter 2.5 (The Latest version) (Upgrade your Flutter version)
- Then create another PR after which I'll further check

**Comment by Mohitmadhav** [comment]
image
@yusriltakeuchi so many conflicts

**Comment by Mohitmadhav** [comment]
> image @yusriltakeuchi so many conflicts due to which app isn't running

Also @yusriltakeuchi you can create an issue for Null safety and tag me there (Also read the guidelines in README)
Then I'll assign

**Comment by Mohitmadhav** [comment]
> > image @yusriltakeuchi so many conflicts due to which app isn't running
> 
> Also @yusriltakeuchi you can create an issue for Null safety and tag me there (Also read the guidelines in README) Then I'll assign

@yusriltakeuchi that Null safety issue has been assigned to someone else. 
But feel free to discuss anything in the Discussions or creating an issue if needed.

Cheers!

**Pull request closed without merging**
