### PR TITLE
User Preference Working Properly

### LINKED ISSUE #130: User Preference Form not getting saved
## Description
- Once you select the genres, the Favourite author and book get erased.
- The Form doesn't save (gives an error when tapped on save)

## Screenshots
image

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Check lib\screens\user_preferences.dart
2. Also, the keyboard should automatically unfocus when the typing gets finished in the text field
3. Show a Snackbar with a message : *User preferences have been saved* when I get saved in the database
4. Database: lib\services\database_service.dart

## Additional data
Add your working gif/screen recording while in the PR.

### PR DESCRIPTION
**Pull request by Samveg12**
# Description

The User Preference textfields dont disappear on clicking on genre preference and gets saved in the database as well 

Fixes #130

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

 Checked whether its getting saved in the database

# Checklist:

https://user-images.githubusercontent.com/68071531/136775583-10c48296-01b7-4498-88ab-c2b7bdf780ee.mov

- [x] My code follows the code of conduct of this project
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
@Samveg12 that's due to linting issues i.e. the warnings which are there in the program. 
After resolving #99, the checks will pass.

**Comment by Mohitmadhav** [comment]
@Samveg12 once tag me when you complete our changes.

**Comment by Samveg12** [comment]
@Mohitmadhav please check i aint getting the error any longer and the snackbar is also getting displayed

**Comment by Samveg12** [comment]
@Mohitmadhav you dont want the saved data of user which he had entered in the user preference before to be showed by default next time he wants to edit it? Also the snack bar isnt visible ?

**Comment by Mohitmadhav** [comment]
No, the snack bar isn't visible bro.
Ok, for now, let it show the saved book and author

**Comment by Samveg12** [comment]
https://user-images.githubusercontent.com/68071531/137847102-60f34010-6aa9-496c-a75b-1dca1f20882f.mov

@Mohitmadhav please check the snackbar is shown after preference is getting saved and have uploaded the video for the same and pushed the changes also

**Comment by Mohitmadhav** [comment]
Ok @Samveg12.
Just pull the latest changes and resolve the conflicts (The app is now migrated to null safety)
Then I'll check it again

**Pull request merged**
