### PR TITLE
Added Saved books (Bookmarks)

### LINKED ISSUE #108: Bookmark not working (Provider State Management)
## Description
The Books should get saved in the **Saved Books** section, once the user bookmarks them but it's not functional right now.

## Screenshots
<div class = "row">

</div>

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Check the book provider file: lib\providers\books.dart
2. Book description file: lib\screens\book_desciption.dart
2. Other provider files: lib\providers
3. Try out by adding a Book from Google Books API then saving it as a bookmark for testing.
4. For that checkout: lib\screens\add_book.dart

## Additional data
Add the screenshots of the saved books while making the pull request.

### PR DESCRIPTION
**Pull request by Samveg12**
# Description

The books are being added to the save section
Fixes #108 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

Screenshot 2021-10-04 at 11 49 35 PM

- [x] My code follows the code of conduct of this project
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
@Samveg12 please tag the issue number too, in the PR.
Fixes # (type your issue number)

**Comment by Samveg12** [comment]
@Mohitmadhav yes done

**Comment by Mohitmadhav** [comment]
@Samveg12 why did you downgrade the packages, is it due to the Null safety problem?

**Comment by Mohitmadhav** [comment]
> @Mohitmadhav yes done

I meant in the description, as I did.
But remember this for further issues bro.

**Comment by Samveg12** [comment]
@Mohitmadhav yes was facing issues so downgraded it

**Comment by Samveg12** [comment]
> > @Mohitmadhav yes done
> 
> I meant in the description, as I did. But remember this for further issues bro.

@Mohitmadhav apologies yes will remember it

**Review by Mohitmadhav — CHANGES_REQUESTED** [review]
@Samveg12 please remember to follow the README guidelines and do
*git pull upstream main* before pushing any changes.

Some changes from previous PRs aren't reflected in your codebase due to which I'm unable to log in. So do this, and commit again in the same PR.

Rest all your changes are fine.

**Comment by Samveg12** [comment]
@Mohitmadhav yes I did that do I have to make another pull request ?

**Review by Mohitmadhav — APPROVED** [review]

**Pull request merged**
