### PR TITLE
Fixed user preferences issue

### LINKED ISSUE #149: Refactor code for Multiple Chip Choice
## Description
This issue is in continuation with issue #130. User preferences are not getting saved due to package issues.

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Create a new class for multiple chips choice.
2. Implement required methods in that class.

### PR DESCRIPTION
**Pull request by keyurgit45**
# Description

Summary of the changes and which issue is fixed. 
User preferences were not getting selected. we are using the chip choice null safety package and now we can select favorite genres and save them in the database. 
Fixes #149

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
image
@keyurgit45 actually I was busy these days will some academics bro..
Just have a look at this error

**Comment by Mohitmadhav** [comment]
This error occurred when I pressed on preferences button...
Wait I'll clean and check again

**Comment by keyurgit45** [comment]
> This error occurred when I pressed on preferences button... Wait I'll clean and check again

Okay. also, there is a problem with explore tab. the books are added again and again when we go to explore tab again.

**Comment by Mohitmadhav** [comment]
Okay, try to resolve it...I'll check too

**Comment by keyurgit45** [comment]
> Okay, try to resolve it...I'll check too

What about this issue? @Mohitmadhav

**Comment by Mohitmadhav** [comment]
> > Okay, try to resolve it...I'll check too
> 
> What about this issue? @Mohitmadhav

Resolve this first bro, then explore wala issue.

**Comment by keyurgit45** [comment]
> > > Okay, try to resolve it...I'll check too
> > 
> > What about this issue? @Mohitmadhav
> 
> Resolve this first bro, then explore wala issue.

I am not getting this error. Try flutter clean.

**Pull request merged**
