### PR TITLE
Edit Profile and Owner's Info tab fixed

### LINKED ISSUE #79: Edit Profile and Owner's Info tab not working (Provider State Management)
## Description
- The Edit Profile Page isn't opening. The error is as shown below.
- Same error occurs in the book description page when tapping on *Owner's Info*
- Try it in your local system first

## Screenshots
image
image

## Steps to Reproduce
This has occurred because the provider hasn't been registered in *main.dart*.

1. So either replace the Provider with *Stream Provider* (Initialized in *home.dart*)
2. OR  Extend the UserData function with ChangeNotifiers with relevant functions(If required)
3. User Model : lib/providers/user.dart
4. Book Description page: lib/screens/book_desciption.dart

## Additional data
What better solution can be there to fix this issue? Go through the entire codebase for more clarity.

### PR DESCRIPTION
**Pull request by keyurgit45**
# Description

Summary of the changes and which issue is fixed. 
Now Edit profile and owners tab is working. A new profile can be updated. Also in location helper removed the state field instead added street address because we can't get state using geocode package. Existing accounts may not work after this. I tested using a new account, it's working fine.

Fixes #79

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

- [x] My code follows the code of conduct of this project
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
I just deleted the whole collection because there were many books like these.
And I again added a book. Just check whether it's displaying in your app or not (For more than 20 km books)?

**Comment by keyurgit45** [comment]
It's working.. But if you delete the books collection you also need to delete ownedbooks collection from each users collections also.

**Comment by Mohitmadhav** [comment]
I can delete the whole user collection also - It already has lot of junk from the past test users

**Comment by Mohitmadhav** [comment]
@keyurgit45 I deleted the user collection too...
So just once test the release apk at your home among your family members to check this error...
Then I'll tell whether it gets displayed in my (>20 km) range or not

**Comment by keyurgit45** [comment]
@Mohitmadhav have you deleted accounts from authentication tab on firebase?

**Comment by Mohitmadhav** [comment]
No, just the user collection from Firestore

**Comment by keyurgit45** [comment]
> No, just the user collection from Firestore

Then delete that also otherwise it will create issues

**Comment by Mohitmadhav** [comment]
Yeah I know @keyurgit45 but they have to be deleted one by one so didn't do so for now

**Comment by keyurgit45** [comment]
> Yeah I know @keyurgit45 but they have to be deleted one by one so didn't do so for now

Okay Fine! I am creating new account then Check if (Book info) it is showing on your phone or not .

**Comment by Mohitmadhav** [comment]
> > Yeah I know @keyurgit45 but they have to be deleted one by one so didn't do so for now
> 
> Okay Fine! I am creating new account then Check if (Book info) it is showing on your phone or not .

I deleted all the accounts from Auth console using website inspect

**Comment by keyurgit45** [comment]
@Mohitmadhav I have added books. check if these books are showing on your device correctly.

**Comment by Mohitmadhav** [comment]
Yeah...now the Owner's info is sorted out.
So, the Provider context you have resolved.
Cool @keyurgit45 .
Now more feature issues are clearly visible.

**Review by Mohitmadhav — APPROVED** [review]

**Pull request merged**
