### PR TITLE
add signup with email

### LINKED ISSUE #83: Email Authentication using Provider and Firebase
## Description
- Setup Email Signup using Firebase and Provider State management
- #56 has already been created for removing the confirmation code page
- Auth user flow is shown below

## Screenshots
image

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Make an auth provider dart file in *lib\providers*
2. All the auth screens are in *lib\screens\auth*
3. Firebase Auth has been set up in *lib\services\auth.dart*

## Additional data
Auth User flow: https://www.figma.com/file/uhWQuE4EKDHR8AqH4p3eFK/Books-App?node-id=0%3A1
Maybe we can reset the password in a better way. Let's discuss it here

### PR DESCRIPTION
**Pull request by keyurgit45**
# Description

Summary of the changes and which issue is fixed. 
I have added sign-up with email and password (firebase). The code for the same is in lib\screens\auth. Added validation for email and password. Also modified the Custom TextEditingField to use textEditingController in order to use the email and password for further sign-up use.

Fixes #83

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x]My code follows the code of conduct of this project
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by keyurgit45** [comment]
Github is showing the branch has some conflicts. but if i remove the code it will give error. what should i do ? @Mohitmadhav

**Comment by Mohitmadhav** [comment]
> Github is showing the branch has some conflicts. but if i remove the code it will give error. what should i do ? @Mohitmadhav

Did you do **git pull upstream main** before pushing your changes?

**Comment by Mohitmadhav** [comment]
> Github is showing the branch has some conflicts. but if i remove the code it will give error. what should i do ? @Mohitmadhav



> Github is showing the branch has some conflicts. but if i remove the code it will give error. what should i do ? @Mohitmadhav

image
Is this the only conflict showing to you?

**Comment by keyurgit45** [comment]
yes this is the only conflict showing to me.

**Comment by Mohitmadhav** [comment]
> > Github is showing the branch has some conflicts. but if i remove the code it will give error. what should i do ? @Mohitmadhav
> 
> Did you do **git pull upstream main** before pushing your changes?

@keyurgit45 ?

**Comment by keyurgit45** [comment]
I did. But i got this ->
$ git pull upstream main
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Mohitmadhav** [comment]
> fatal: 'upstream' does not appear to be a git repository
> fatal: Could not read from remote repository.

try out
*git remote add upstream https://github.com/Project-Easter/Flutter-UI*

Then again *git pull upstream main*

**Comment by Mohitmadhav** [comment]
@keyurgit45 I'm getting null uid when I login
image

**Comment by keyurgit45** [comment]
I implemented sign up with Email not login

**Comment by Mohitmadhav** [comment]
> I implemented sign up with Email not login. Also the app is missing log out feature.

Yeah, I assigned Google Sign out to someone else. 
Also, I was creating another issue for login and logout so you can work on that too if you want.

**Comment by keyurgit45** [comment]
> > I implemented sign up with Email not login. Also the app is missing log out feature.
> 
> Yeah, I assigned Google Sign out to someone else. Also, I was creating another issue for login and logout so you can work on that too if you want.

Sure, I would Like to work on them.

**Comment by Mohitmadhav** [comment]
> > > I implemented sign up with Email not login. Also the app is missing log out feature.
> > 
> > 
> > Yeah, I assigned Google Sign out to someone else. Also, I was creating another issue for login and logout so you can work on that too if you want.
> 
> Sure, I would Like to work on them.

Cool, the issue will be ready within a few minutes.

**Comment by keyurgit45** [comment]
> > > > I implemented sign up with Email not login. Also the app is missing log out feature.
> > > 
> > > 
> > > Yeah, I assigned Google Sign out to someone else. Also, I was creating another issue for login and logout so you can work on that too if you want.
> > 
> > 
> > Sure, I would Like to work on them.
> 
> Cool, the issue will be ready within a few minutes.

Thank you for your help. This is my first open-source contribution. Also, can you remove my email id's from firebase that I used for testing purpose?

**Comment by Mohitmadhav** [comment]
> > > > > I implemented sign up with Email not login. Also the app is missing log out feature.
> > > > 
> > > > 
> > > > Yeah, I assigned Google Sign out to someone else. Also, I was creating another issue for login and logout so you can work on that too if you want.
> > > 
> > > 
> > > Sure, I would Like to work on them.
> > 
> > 
> > Cool, the issue will be ready within a few minutes.
> 
> Thank you for your help. This is my first open-source contribution. Also, can you remove my email id's from firebase that I used for testing purpose?

No problem bro. 
Sure, will remove those email ids from firebase.

**Pull request merged**
